name: Lint
on: 'push'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run brakeman
        run: bundle exec brakeman
      - name: Run bundle audit
        run: bundle exec bundle-audit
      - name: Run rubocop
        run: bundle exec rubocop
