name: Test
on: 'push'

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: insideman
          POSTGRES_PASSWORD: insideman
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup DB
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DATABASE: insideman_test
          POSTGRES_USERNAME: insideman
          POSTGRES_PASSWORD: insideman
          RAILS_ENV: test
        run: bin/rails db:create db:schema:load

      - name: Run tests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DATABASE: insideman_test
          POSTGRES_USERNAME: insideman
          POSTGRES_PASSWORD: insideman
          RAILS_ENV: test
        run: bundle exec rspec
